name: 'Run Elasticsearch'
description: 'This action spins up Elasticsearch instance that can be accesssd and used in your subsquent steps.'
author: 'tejash'

branding:
  icon: 'database'
  color: 'green'

inputs:
  stack-version:
    description: 'The version of the Elastic Stack you want to run'
    required: true
  nodes:
    description: 'Number of nodes in the cluster'
    required: false
    default: 1
  plugins:
    description: 'Elasticsearch plugin strings'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    STACK_VERSION: ${{ inputs.stack-version }}
    NODES: ${{ inputs.nodes }}
    PLUGINS: ${{ inputs.plugins }}
